const markdown = (sections: string[]) => sections.join("\n\n");

const author = {
  authorName: "Khushpreet",
  authorBio: "Software engineer writing about JavaScript, React, Node.js, distributed systems, Docker, AWS, and cloud infrastructure.",
  authorAvatar: "/noavatar.png",
};

export const supersededSeedSlugs = [
  "practical-mental-model-react-server-components",
  "typescript-works-best-at-the-boundaries",
  "container-queries-changed-how-i-build-components",
  "you-probably-need-less-react-state",
  "accessibility-is-a-component-api-problem",
  "systematic-way-debug-hydration-mismatches",
  "web-performance-starts-before-lighthouse",
  "design-tokens-are-decisions-not-variables",
  "forms-are-distributed-systems-in-miniature",
  "how-i-decide-where-frontend-code-should-live",
] as const;

export const seedPosts = [
  {
    ...author,
    title: "The JavaScript event loop beyond the usual diagram",
    slug: "javascript-event-loop-beyond-the-usual-diagram",
    desc: "The event loop makes more sense when you follow one turn through the call stack, microtask checkpoint, rendering opportunity, and next task.",
    excerpt: "Move beyond the stack-and-queue diagram by tracing what actually happens between a task, its microtasks, and the browser’s next rendering opportunity.",
    content: markdown([
      "Most explanations of the JavaScript event loop stop at a call stack and a callback queue. That picture is useful, but it hides the part that causes production bugs: the browser does not treat every queued callback equally, and rendering does not happen after every line of JavaScript.",
      "## A turn starts with a task",
      "A timer callback, user interaction, parser event, or message event begins as a task. The browser runs that task to completion. JavaScript is not interrupted halfway through a synchronous function, which is why a long calculation can block input even when the rest of the application is asynchronous.",
      "```js\nconsole.log('task start')\n\nsetTimeout(() => console.log('next task'), 0)\nPromise.resolve().then(() => console.log('microtask'))\n\nconsole.log('task end')\n// task start, task end, microtask, next task\n```",
      "The zero-millisecond timer does not run immediately. It schedules a future task. The promise reaction enters the microtask queue, which is drained after the current stack becomes empty and before the event loop moves to another task.",
      "## Microtasks can delay the whole browser",
      "At the end of a task, the browser performs a microtask checkpoint. It keeps draining microtasks until the queue is empty—including new microtasks created by existing microtasks. An accidental recursive promise chain can therefore starve timers, input, and painting without containing a traditional infinite loop.",
      "```js\nfunction starve() {\n  queueMicrotask(starve)\n}\nstarve()\n```",
      "This is also why splitting expensive work with `Promise.resolve().then(...)` does not make the page responsive. It moves work into microtasks but still prevents the event loop from reaching a rendering opportunity. Yield with a task-producing mechanism, a scheduler API, or a worker when the work is substantial.",
      "## Rendering is an opportunity, not a guarantee",
      "After microtasks, the browser may update rendering before choosing the next task. It can skip a frame when nothing changed or when the display cadence does not require one. `requestAnimationFrame` callbacks run as part of the rendering lifecycle, making them appropriate for visual updates—not general background work.",
      "The practical mental model is: run one task, empty microtasks, possibly render, then choose another task. When an interface freezes, ask which phase keeps producing work. That question is much more diagnostic than asking whether the code is asynchronous.",
    ]),
    img: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1800&q=85",
    category: "JavaScript",
    tags: ["JavaScript", "Event Loop", "Browser"],
    featured: true,
    published: true,
    publishedAt: new Date("2026-08-24T09:00:00.000Z"),
  },
  {
    ...author,
    title: "WebSockets or Server-Sent Events? Choose from failure modes",
    slug: "websockets-or-server-sent-events-failure-modes",
    desc: "The right real-time transport depends less on popularity and more on directionality, reconnect behavior, infrastructure, and delivery semantics.",
    excerpt: "WebSockets and SSE are easy to compare by features. The better choice appears when you compare how each behaves during disconnects, deploys, and load spikes.",
    content: markdown([
      "Real-time architecture discussions often reduce the decision to one question: do you need two-way communication? That is a good first filter, but production systems are decided by what happens when connections fail, instances restart, proxies time out, and clients miss events.",
      "## SSE is an HTTP response that stays open",
      "Server-Sent Events send UTF-8 text from server to browser over a normal HTTP connection. The browser exposes a small `EventSource` API and automatically reconnects. Events can include an `id`, allowing the client to send `Last-Event-ID` after a disconnect so the server can resume from a known position.",
      "```js\nconst stream = new EventSource('/api/deployments/stream')\nstream.addEventListener('status', event => {\n  updateDeployment(JSON.parse(event.data))\n})\n```",
      "That makes SSE excellent for notifications, job progress, dashboards, and AI token streaming where the client already uses HTTP requests to send commands. It also fits existing authentication, observability, and proxy infrastructure more naturally than a separate protocol upgrade.",
      "## WebSockets create a bidirectional session",
      "A WebSocket is appropriate when the server and client both send frequent low-latency messages: collaborative editing, multiplayer state, presence, or an interactive terminal. The protocol gives you frames and a connection—not message durability, retries, ordering across reconnects, or authorization rules. Those remain application responsibilities.",
      "## Design the reconnect path first",
      "Both transports disconnect. Mobile devices change networks, load balancers rotate targets, and deployments terminate instances. A reconnecting client needs a way to recover state. Sequence numbers, resumable offsets, or a fresh snapshot followed by live events are architectural requirements, not optional polish.",
      "A common design stores durable domain events in a broker or database and treats the socket server as a delivery edge. The edge can disappear without becoming the system of record. Clients reconnect, present their last acknowledged position, and receive either missed events or a new snapshot.",
      "## Infrastructure changes the answer",
      "Check idle timeouts, maximum connection duration, connection quotas, and whether your platform supports graceful draining. Long-lived connections also change autoscaling: request rate becomes less useful than active connections, outbound messages, and per-instance memory.",
      "I default to SSE for server-to-browser updates because it is simpler and has useful browser reconnect semantics. I choose WebSockets when the product truly needs a bidirectional session. In both cases, the important design is the recovery protocol around the connection—not the connection itself.",
    ]),
    img: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1800&q=85",
    category: "Real-time",
    tags: ["WebSockets", "SSE", "System Design"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-08-18T09:00:00.000Z"),
  },
  {
    ...author,
    title: "React performance: measure renders before memoizing",
    slug: "react-performance-measure-renders-before-memoizing",
    desc: "React performance work becomes predictable when you separate render frequency, render cost, commit cost, and network latency.",
    excerpt: "Before adding memoization, identify whether the real problem is repeated rendering, expensive rendering, a costly commit, or something outside React entirely.",
    content: markdown([
      "A slow React screen often attracts the same first response: add `useMemo`, wrap components in `memo`, and stabilize callbacks. Those tools can help, but applying them before measuring creates more comparison work and can leave the actual bottleneck untouched.",
      "## Separate frequency from cost",
      "A component rendering often is not automatically a problem. A small component can render hundreds of times without becoming visible in a trace. A chart that renders once may still block the main thread. Use the React Profiler to answer two different questions: which components render during the interaction, and which renders consume meaningful time?",
      "The browser performance panel adds the rest of the picture. It shows long tasks, style calculation, layout, paint, scripting outside React, and network gaps. If React finishes in 8ms but layout takes 140ms, memoizing props is not the solution.",
      "## Fix ownership before caching calculations",
      "State placed too high in the tree expands the render surface. Move rapidly changing state closer to the interaction that owns it, or split a stable subtree so it is passed as children. This architectural change often removes more work than a collection of memoization wrappers.",
      "```tsx\nfunction SearchPage() {\n  return (\n    <SearchProvider>\n      <SearchInput />\n      <SearchResults />\n    </SearchProvider>\n  )\n}\n```",
      "The provider should expose the smallest useful values, and consumers should subscribe only to what they need. A single context object containing state, actions, loading flags, and unrelated settings causes every consumer to wake up whenever any part changes.",
      "## Memoization has a cost model",
      "`memo` compares props, `useMemo` stores a value, and `useCallback` stores a function reference. Each adds allocation, dependency tracking, and conceptual overhead. They pay off when the avoided work is more expensive than maintaining the cache and when references remain stable enough to hit it.",
      "## Optimize the interaction, not the component",
      "For large updates, consider whether every result must render immediately. Virtualize long lists, defer non-urgent updates, paginate data, and move heavy computation off the main thread. React transitions can preserve input responsiveness, but they do not make expensive work free.",
      "My workflow is consistent: reproduce on a production build, record the interaction, identify the longest blocking region, determine whether React owns it, and make one change. Performance improves faster when every optimization begins with evidence and ends with another trace.",
    ]),
    img: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=1800&q=85",
    category: "React",
    tags: ["React", "Performance", "Profiling"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-08-11T09:00:00.000Z"),
  },
  {
    ...author,
    title: "How concurrent rendering changes the way React feels",
    slug: "how-concurrent-rendering-changes-react",
    desc: "Concurrent React is not parallel rendering. It is the ability to prioritize, pause, discard, and restart render work before committing it.",
    excerpt: "Concurrent rendering is easier to reason about when you see it as interruptible preparation with an atomic commit—not as background threads for components.",
    content: markdown([
      "The word concurrent suggests that React renders several components at the same instant. In the browser, most application JavaScript still runs on one main thread. React’s important capability is different: render work can be interruptible, prioritized, restarted, and even discarded before it reaches the DOM.",
      "## Render prepares; commit changes the world",
      "React’s render phase calculates what the UI should become. The commit phase applies those changes and runs layout effects. Concurrent rendering makes preparation interruptible, but the commit remains atomic from the user’s perspective. The browser never displays half of one React commit.",
      "This explains a core rule: rendering must stay pure. A component can be evaluated more than once without committing. Starting a request, mutating a global, or writing to storage during render can therefore create work that does not correspond to any visible UI.",
      "## Urgent and non-urgent updates",
      "Typing into an input is urgent because every keystroke must feel immediate. Updating a large search result list can be non-urgent. A transition lets React prioritize the input and restart result rendering when another character arrives.",
      "```tsx\nconst [query, setQuery] = useState('')\nconst [filter, setFilter] = useState('')\n\nfunction onChange(value: string) {\n  setQuery(value)\n  startTransition(() => setFilter(value))\n}\n```",
      "The transition does not delay a network request automatically or make filtering faster. It changes the scheduling priority so stale preparation can be abandoned. If the filtering calculation itself monopolizes the thread inside one long function, it may still need restructuring or a worker.",
      "## Suspense defines a reveal strategy",
      "A Suspense boundary is not just a spinner location. It says which region may wait independently and which existing content should remain visible during an update. Boundary placement controls whether navigation feels stable or whether the entire screen flashes to a fallback.",
      "## Effects observe committed reality",
      "Because prepared renders can be discarded, effects belong to committed UI. Cleanup must fully undo setup, and code should tolerate setup-cleanup cycles during development. Thinking in terms of synchronization with a committed external resource makes effects far easier to design.",
      "Concurrent React feels better when urgent feedback is small, non-urgent work is interruptible, and loading boundaries match the product’s visual structure. The feature is scheduling—not magic parallelism—and that mental model makes its tradeoffs much clearer.",
    ]),
    img: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1800&q=85",
    category: "React",
    tags: ["React", "Concurrency", "Suspense"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-08-03T09:00:00.000Z"),
  },
  {
    ...author,
    title: "Backpressure is the hidden contract in Node.js streams",
    slug: "backpressure-hidden-contract-nodejs-streams",
    desc: "Streams stay memory-efficient only when producers respect the rate at which downstream consumers can accept data.",
    excerpt: "Node.js streams are not memory-efficient by default; they become efficient when every stage respects backpressure instead of buffering without a limit.",
    content: markdown([
      "Streams are often introduced as a way to process files without loading everything into memory. That is true only when data producers respect consumers. If a fast source keeps writing while a slow destination falls behind, the application has simply moved the full dataset into an ever-growing memory buffer.",
      "## The boolean returned by write matters",
      "A writable stream returns `false` when its internal buffer has reached the high-water mark. That is a request to pause. Resume after the `drain` event, when the destination has processed enough buffered data.",
      "```js\nasync function writeChunks(writable, chunks) {\n  for await (const chunk of chunks) {\n    if (!writable.write(chunk)) {\n      await once(writable, 'drain')\n    }\n  }\n  writable.end()\n}\n```",
      "Ignoring the return value may appear fine in local testing because disks and loopback networks are fast. Under a slow client or remote object store, buffered data grows, garbage collection becomes expensive, and the process can be terminated for exceeding its memory limit.",
      "## Use pipeline for lifecycle management",
      "`stream.pipeline` connects backpressure and also coordinates errors and cleanup across every stage. If compression fails, the file reader and HTTP response should not remain open. The promise-based API makes that lifecycle explicit.",
      "```js\nawait pipeline(\n  createReadStream(input),\n  createGzip(),\n  createWriteStream(output)\n)\n```",
      "Transform streams must follow the same contract. Call the transform callback only when the transformed chunk is ready, and avoid starting unlimited asynchronous work inside `_transform`. If a transform performs remote calls, add an intentional concurrency limit.",
      "## Backpressure crosses service boundaries",
      "The concept is larger than Node’s stream classes. A queue consumer, WebSocket broadcaster, CSV exporter, and database pagination loop all need a policy for a slow downstream dependency. That policy may be pausing, bounding concurrency, dropping replaceable updates, or spilling durable work to a queue.",
      "When diagnosing memory growth, measure buffered bytes, active operations, downstream latency, and event-loop delay. Streams solve large-data processing only when flow control remains intact from the original source to the final destination.",
    ]),
    img: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1800&q=85",
    category: "Node.js",
    tags: ["Node.js", "Streams", "Performance"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-07-25T09:00:00.000Z"),
  },
  {
    ...author,
    title: "Designing idempotent APIs in Node.js",
    slug: "designing-idempotent-apis-nodejs",
    desc: "Retries are unavoidable in distributed systems, so write endpoints need a way to distinguish a repeated request from a new intention.",
    excerpt: "A reliable Node.js API assumes clients and infrastructure will retry—and gives repeated requests the same observable result without repeating the side effect.",
    content: markdown([
      "A client sends a payment request and the connection times out. Did the server reject it, finish it, or commit the database write before the response was lost? The client cannot know, so it retries. Without idempotency, a normal network failure becomes a duplicate side effect.",
      "## Idempotency describes an observable result",
      "An operation is idempotent when repeating the same intention produces the same externally visible outcome. `GET` and `DELETE` are naturally close to that model. Creating a payment, order, or background job usually needs an explicit idempotency key generated by the client.",
      "```http\nPOST /payments\nIdempotency-Key: 4e93a2d8-...\nContent-Type: application/json\n```",
      "The server stores the key with a fingerprint of the request and the completed response. A retry with the same key and payload returns the stored result. The same key with a different payload is rejected, because silently treating two different intentions as one hides a client bug.",
      "## The key and side effect must commit together",
      "Checking for a key and then performing a write in separate unprotected steps creates a race: two requests can both observe that the key is absent. Use a unique database constraint and a transaction when the datastore supports it. One request wins ownership; the other waits for or reads the result.",
      "In Node.js, do not rely on an in-memory map. It disappears during deployment, is not shared across instances, and cannot coordinate concurrent workers. Persist the record in the same reliability domain as the operation.",
      "## Model in-progress and failed attempts",
      "The idempotency record usually needs `processing`, `completed`, and recoverable failure states. A crashed worker may leave a lease that another worker can reclaim after a timeout. Permanent validation failures can be stored and replayed, while transient infrastructure failures may allow a controlled retry.",
      "## Idempotency does not replace domain constraints",
      "A user can intentionally send two requests with different keys. Business rules still need uniqueness constraints, inventory checks, or a ledger. The idempotency layer protects transport retries; the domain model protects meaning.",
      "The most reliable APIs make retries boring. Give every side-effecting operation a stable identity, enforce it atomically, and return the original result. That turns ambiguous network outcomes into a normal code path instead of an incident.",
    ]),
    img: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1800&q=85",
    category: "Node.js",
    tags: ["Node.js", "API Design", "Distributed Systems"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-07-16T09:00:00.000Z"),
  },
  {
    ...author,
    title: "Production Docker images for Node.js without the bloat",
    slug: "production-docker-images-nodejs-without-bloat",
    desc: "A good Node.js container image is reproducible, minimal, non-root, cache-friendly, and explicit about what production actually needs.",
    excerpt: "Multi-stage builds help, but reliable Node.js containers also require deliberate dependency installation, signal handling, security, and build context control.",
    content: markdown([
      "A Dockerfile that starts with `FROM node`, copies the repository, and runs `npm install` will probably work. It can also produce a huge image, invalidate its cache on every source edit, include development secrets, and run the application as root.",
      "## Separate dependency, build, and runtime concerns",
      "A multi-stage build makes each responsibility visible. Copy lockfiles before source code so dependency installation remains cached when only application files change. Use `npm ci` for a reproducible dependency graph.",
      "```dockerfile\nFROM node:22-bookworm-slim AS deps\nWORKDIR /app\nCOPY package.json package-lock.json ./\nRUN npm ci\n\nFROM deps AS build\nCOPY . .\nRUN npm run build && npm prune --omit=dev\n\nFROM node:22-bookworm-slim AS runtime\nENV NODE_ENV=production\nWORKDIR /app\nCOPY --from=build --chown=node:node /app/dist ./dist\nCOPY --from=build --chown=node:node /app/node_modules ./node_modules\nCOPY --from=build --chown=node:node /app/package.json ./\nUSER node\nCMD [\"node\", \"dist/server.js\"]\n```",
      "The exact stages vary for workspaces and native dependencies, but the runtime stage should contain only what the process needs. A smaller image reduces transfer time and attack surface; it does not excuse keeping the base image patched.",
      "## Treat the build context as input",
      "Docker sends the build context to the builder before running instructions. A `.dockerignore` should exclude Git history, local environment files, logs, test output, editor state, and dependency directories. This protects cache performance and reduces the chance of copying credentials into an intermediate layer.",
      "## Run as a real process",
      "Node should receive termination signals and have time to stop accepting traffic, finish in-flight requests, and close connections. Use exec-form `CMD`, handle `SIGTERM`, and align the application’s shutdown timeout with the orchestrator’s grace period.",
      "## Pin what you can reproduce",
      "Pin the major Node runtime intentionally and use the lockfile for packages. For stricter supply-chain control, pin the base image digest through automation that also refreshes it. Reproducibility is useful only if security updates still have a path into production.",
      "A production image is an artifact, not a development environment. Build it once, scan it, promote the same digest, inject configuration at runtime, and keep the final stage boring enough to audit in a minute.",
    ]),
    img: "https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=1800&q=85",
    category: "Docker",
    tags: ["Docker", "Node.js", "DevOps"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-07-07T09:00:00.000Z"),
  },
  {
    ...author,
    title: "A practical path from Docker Compose to Amazon ECS",
    slug: "docker-compose-to-amazon-ecs",
    desc: "Moving containers to ECS is less about translating YAML and more about making networking, identity, health, deployment, and observability explicit.",
    excerpt: "ECS becomes easier when you map the responsibilities hidden by local Docker Compose: networking, secrets, health checks, identity, logs, and safe deployments.",
    content: markdown([
      "Docker Compose is excellent for describing a local application, but it quietly inherits a developer machine’s network, filesystem, credentials, and lifecycle. Moving to Amazon ECS means those assumptions must become explicit infrastructure decisions.",
      "## Map services to deployment units",
      "An ECS task definition describes one deployable unit. Containers that must share a lifecycle—such as an application and a tightly coupled telemetry sidecar—can live in one task. A database usually should not. Managed services such as RDS and ElastiCache have durability and operational models that are different from an application task.",
      "Choose Fargate when you want AWS to manage the container hosts and the workload fits its model. EC2 capacity can make sense for specialized hardware, daemon workloads, or cost optimization at sustained scale. The application image should work in either case.",
      "## Networking becomes part of application design",
      "In `awsvpc` mode, tasks receive network interfaces and security groups. Put application tasks in private subnets, expose them through an Application Load Balancer when HTTP ingress is needed, and allow only the required traffic between security groups.",
      "Health checks have two layers. The container health check answers whether the process is internally healthy. The load balancer target check answers whether the service should receive traffic. A shallow `/health` endpoint can keep a broken instance in rotation; a check that depends on every external system can cause a regional dependency failure to restart the whole fleet. Define readiness deliberately.",
      "## Give the task an identity",
      "Use an ECS task role for AWS API access instead of distributing access keys. The execution role is for ECS operations such as pulling an image or sending logs; the task role is what application code assumes. Keeping them separate makes least privilege much clearer.",
      "## Deploy with rollback signals",
      "A rolling deployment needs enough healthy capacity to overlap old and new tasks. Configure graceful shutdown so draining targets stop receiving requests before the process exits. ECS deployment circuit breakers and CloudWatch alarms can stop or roll back a release that never stabilizes.",
      "The migration is complete when the service is operable, not merely running: logs have request context, metrics describe saturation and failures, secrets come from a managed store, and a failed release has a tested recovery path. ECS supplies orchestration primitives; reliability comes from how intentionally you connect them.",
    ]),
    img: "https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?auto=format&fit=crop&w=1800&q=85",
    category: "AWS",
    tags: ["AWS", "ECS", "Docker"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-06-27T09:00:00.000Z"),
  },
  {
    ...author,
    title: "Event-driven AWS systems without the service maze",
    slug: "event-driven-aws-without-service-maze",
    desc: "EventBridge, SNS, SQS, and Lambda solve different coordination problems; using all of them by default creates infrastructure without clarity.",
    excerpt: "Choose AWS messaging services by the delivery and coupling problem you actually have, then design retries, idempotency, and observability as one system.",
    content: markdown([
      "AWS makes it easy to connect a producer to EventBridge, fan out through SNS, buffer in SQS, and process with Lambda. Every service can be justified individually, yet the complete system may become difficult to trace, replay, and explain. The goal is not to use fewer icons; it is to give every hop one clear responsibility.",
      "## Start with the communication contract",
      "An event says something happened. A command asks a specific capability to do something. Mixing the two creates ambiguous ownership. `OrderPlaced` can have several independent consumers. `ChargePayment` has an intended owner and a success or failure that the caller cares about.",
      "Use EventBridge when producers should publish domain events without knowing subscribers and routing rules belong in infrastructure. Use SNS for straightforward push fan-out. Use SQS when a consumer needs buffering, controlled concurrency, and independent retry behavior. Lambda is a compute choice, not a messaging guarantee.",
      "## Assume at-least-once delivery",
      "Messages can be delivered more than once. A visibility timeout can expire while processing continues, a client can retry a publish, or a service can recover from an internal failure. Consumers need an idempotency boundary based on a stable event or operation ID.",
      "Dead-letter queues are not a failure strategy by themselves. Decide who owns them, which alarms fire, how payloads are inspected safely, and whether replay preserves ordering or triggers outdated side effects. A queue that silently collects failures is delayed data loss.",
      "## Put correlation into the envelope",
      "Every event should carry an event ID, type, version, timestamp, source, and correlation identifiers that connect it to the originating request or workflow. Business payloads evolve independently, so consumers should tolerate additive fields and reject unsupported major versions explicitly.",
      "## Observe the path, not only functions",
      "Measure event age, queue depth, oldest-message age, retry counts, dead-letter volume, and end-to-end completion time. Function error rate alone can look healthy while a queue grows for hours. Structured logs should include the same event and correlation IDs at every hop.",
      "A good event-driven design can be drawn as a short sentence: who emits the fact, where it is buffered or routed, who owns the side effect, and how failure is recovered. Add a service only when that sentence gains a capability you can name and operate.",
    ]),
    img: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1800&q=85",
    category: "AWS",
    tags: ["AWS", "Event-Driven", "Architecture"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-06-16T09:00:00.000Z"),
  },
  {
    ...author,
    title: "Caching is easy; invalidation is the system",
    slug: "caching-is-easy-invalidation-is-the-system",
    desc: "A cache is not just a fast key-value lookup. It is a second copy of truth with rules about identity, staleness, ownership, and recovery.",
    excerpt: "Caching becomes a system-design problem the moment a second copy of data can outlive the request that created it. Start with acceptable staleness, not Redis.",
    content: markdown([
      "Adding a cache is easy: choose a key, store a value, and return it before querying the slower source. The difficult part begins when the source changes. The application now owns two representations of truth and must define how long they may disagree.",
      "## Start with the staleness budget",
      "Ask how wrong the value may be and for how long. Product catalog text might tolerate minutes. Authorization and account balance data may not. A time-to-live is a business consistency decision expressed as a number, not a generic performance setting.",
      "Cache-aside works well when misses are acceptable: read the cache, load from the source on a miss, then populate. It also allows a thundering herd when a popular key expires. Request coalescing, jittered expirations, and stale-while-revalidate can keep one expiration from becoming a database incident.",
      "```js\nconst cached = await cache.get(key)\nif (cached) return cached\n\nreturn singleFlight(key, async () => {\n  const value = await database.load(id)\n  await cache.set(key, value, { ttl: withJitter(300) })\n  return value\n})\n```",
      "## Keys are part of the data model",
      "A key must include every input that changes the result: tenant, locale, permissions, query version, and relevant feature flags. Omitting one dimension can leak data or serve a structurally incompatible response. Versioned key prefixes make schema changes and bulk invalidation safer.",
      "## Invalidate from committed change",
      "Deleting a cache entry before a database transaction commits creates a race where another request repopulates old data. Invalidate after the source of truth confirms the write, often through an outbox or change event. Consumers should tolerate duplicate invalidation messages because deletion is naturally idempotent.",
      "For some data, updating the cache directly is worthwhile. For others, deletion is safer because the next reader rebuilds from authoritative state. The choice depends on write volume, read latency, and how much coordination the system can reliably maintain.",
      "## Design for cache loss",
      "A cache should improve the system, not become an undocumented source of truth. Test cold starts and full eviction. Protect the database with concurrency limits and gradual warming. Monitor hit ratio alongside latency, eviction rate, memory pressure, and source load.",
      "The useful design document for a cache names the source of truth, key shape, staleness budget, population strategy, invalidation trigger, and cold-cache behavior. Once those are explicit, choosing Redis, an in-process LRU, or a CDN becomes the smaller decision it should be.",
    ]),
    img: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1800&q=85",
    category: "Architecture",
    tags: ["Caching", "Redis", "System Design"],
    featured: false,
    published: true,
    publishedAt: new Date("2026-06-05T09:00:00.000Z"),
  },
] as const;
